Updated and Improved README.md
denoland/deno_website2 pull request #1538
Opened 2020-10-01 04:35 UTC by surajphulara

Corrected spelling mistakes and grammatical errors

2020-10-01 04:52 UTC, kitsonk requested changes

2020-10-01 04:52 UTC, kitsonk commented on README.md
> +This website consists of two parts :
```suggestion
This website consists of two parts:
```

2020-10-01 04:52 UTC, kitsonk commented on README.md
> +Deno with minimal inerruption in developer flow  (in particular, we need the ability
```suggestion
Deno with minimal interruption in developer flow (in particular, we need the ability
```

2020-10-01 04:54 UTC, kitsonk commented
You also need to get CI to pass before we will consider this PR (basically it is failing because you are not running the linter).

2020-10-01 12:35 UTC, surajphulara commented
> You also need to get CI to pass before we will consider this PR (basically it is failing because you are not running the linter).
please guide me how to do that

2020-10-01 12:41 UTC, lucacasonato commented
Clone the repository and run `yarn format`

2020-10-23 23:46 UTC, lucacasonato commented
Closing due to inactivity.

2020-10-23 23:46 UTC, closed without merging