update(version): to deno v.1.6.1 and std 0.81.0
denoland/deno_website2 pull request #1620
Opened 2020-12-14 23:25 UTC by buttercubz

2020-12-14 23:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_website2?pullRequest=1620) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_website2?pullRequest=1620) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_website2?pullRequest=1620) it.</sub>

2020-12-15 01:05 UTC, lucacasonato requested changes
Blocking for now, as I need to publish the manual. Will do first thing tomorrow morning.

2020-12-15 12:12 UTC, lucacasonato approved these changes
LGTM - can you sign the CLA please?

2020-12-15 13:03 UTC, buttercubz commented
> LGTM - can you sign the CLA please?

done!

2020-12-15 13:04 UTC, merged